-- ==========================================================
-- Supabase Schema Definition for CHECKS Table
-- Universal Early Warning System for Website Failures
-- ==========================================================

-- 1. Create the CHECKS table matching Python & Next.js schemas
CREATE TABLE IF NOT EXISTS public."CHECKS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status_code INT,
    response_ms INT,
    is_up BOOLEAN NOT NULL DEFAULT FALSE,
    ssl_days_left INT
);

-- 2. Create performance indexes for fast dashboard queries
CREATE INDEX IF NOT EXISTS idx_checks_url_time ON public."CHECKS" (url, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_checks_checked_at ON public."CHECKS" (checked_at DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public."CHECKS" ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for Public Access (Next.js dashboard read & Python engine insert)
CREATE POLICY "Allow public read access" 
ON public."CHECKS" 
FOR SELECT 
USING (true);

CREATE POLICY "Allow service and anon insert access" 
ON public."CHECKS" 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow service and anon update access" 
ON public."CHECKS" 
FOR UPDATE 
USING (true);
